trigger:
- master

pool:
  name: Default

steps:
- task: Docker@2
  displayName: Build and push an image to Docker Hub
  inputs:
    command: buildAndPush
    repository: vianrove/api-clientes
    Dockerfile: '**/Dockerfile'
    buildContext: .
    containerRegistry: 'Docker Hub'
    tags: |
      latest